// Generated by `mcp__supabase__generate_typescript_types` against the live
// ysjjgzakswaohmnaowmv project. Do not hand-edit. Regenerate after every
// migration and commit the diff in the same commit as the migration that
// caused it.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      achievements: {
        Row: {
          created_at: string
          description: string
          icon: string
          id: string
          key: string
          title: string
        }
        Insert: {
          created_at?: string
          description: string
          icon?: string
          id?: string
          key: string
          title: string
        }
        Update: {
          created_at?: string
          description?: string
          icon?: string
          id?: string
          key?: string
          title?: string
        }
        Relationships: []
      }
      admin_notifications: {
        Row: {
          audience_id: string | null
          audience_type: string
          created_at: string
          created_by: string | null
          cta_href: string | null
          cta_label: string | null
          id: string
          message: string
          recipient_count: number
          scheduled_at: string | null
          sent_at: string | null
          severity: string
          title: string
        }
        Insert: {
          audience_id?: string | null
          audience_type: string
          created_at?: string
          created_by?: string | null
          cta_href?: string | null
          cta_label?: string | null
          id?: string
          message: string
          recipient_count?: number
          scheduled_at?: string | null
          sent_at?: string | null
          severity?: string
          title: string
        }
        Update: {
          audience_id?: string | null
          audience_type?: string
          created_at?: string
          created_by?: string | null
          cta_href?: string | null
          cta_label?: string | null
          id?: string
          message?: string
          recipient_count?: number
          scheduled_at?: string | null
          sent_at?: string | null
          severity?: string
          title?: string
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          metadata: Json
          target_id: string | null
          target_type: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type?: string | null
        }
        Relationships: []
      }
      campaigns: {
        Row: {
          created_at: string
          ends_at: string | null
          id: string
          name: string
          slug: string
          starts_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          ends_at?: string | null
          id?: string
          name: string
          slug: string
          starts_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          ends_at?: string | null
          id?: string
          name?: string
          slug?: string
          starts_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      challenge_options: {
        Row: {
          challenge_id: string
          id: string
          is_correct: boolean
          label: string
          order_index: number
        }
        Insert: {
          challenge_id: string
          id?: string
          is_correct?: boolean
          label: string
          order_index?: number
        }
        Update: {
          challenge_id?: string
          id?: string
          is_correct?: boolean
          label?: string
          order_index?: number
        }
        Relationships: [
          {
            foreignKeyName: "challenge_options_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "challenges"
            referencedColumns: ["id"]
          },
        ]
      }
      challenges: {
        Row: {
          config: Json
          created_at: string
          id: string
          mission_id: string
          order_index: number
          prompt: string
          type: string
          updated_at: string
        }
        Insert: {
          config?: Json
          created_at?: string
          id?: string
          mission_id: string
          order_index?: number
          prompt: string
          type: string
          updated_at?: string
        }
        Update: {
          config?: Json
          created_at?: string
          id?: string
          mission_id?: string
          order_index?: number
          prompt?: string
          type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "challenges_mission_id_fkey"
            columns: ["mission_id"]
            isOneToOne: false
            referencedRelation: "missions"
            referencedColumns: ["id"]
          },
        ]
      }
      countries: {
        Row: {
          created_at: string
          flag_emoji: string | null
          id: string
          iso_code: string
          name: string
        }
        Insert: {
          created_at?: string
          flag_emoji?: string | null
          id?: string
          iso_code: string
          name: string
        }
        Update: {
          created_at?: string
          flag_emoji?: string | null
          id?: string
          iso_code?: string
          name?: string
        }
        Relationships: []
      }
      entities: {
        Row: {
          country_id: string
          created_at: string
          id: string
          name: string
        }
        Insert: {
          country_id: string
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          country_id?: string
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "entities_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      event_photos: {
        Row: {
          caption: string | null
          created_at: string
          id: string
          moderated_at: string | null
          moderated_by: string | null
          player_id: string
          status: string
          storage_path: string
        }
        Insert: {
          caption?: string | null
          created_at?: string
          id?: string
          moderated_at?: string | null
          moderated_by?: string | null
          player_id: string
          status?: string
          storage_path: string
        }
        Update: {
          caption?: string | null
          created_at?: string
          id?: string
          moderated_at?: string | null
          moderated_by?: string | null
          player_id?: string
          status?: string
          storage_path?: string
        }
        Relationships: []
      }
      game_days: {
        Row: {
          campaign_id: string
          created_at: string
          created_by: string | null
          day_number: number
          id: string
          status: string
          theme: string | null
          title: string
          unlock_at: string | null
          updated_at: string
        }
        Insert: {
          campaign_id: string
          created_at?: string
          created_by?: string | null
          day_number: number
          id?: string
          status?: string
          theme?: string | null
          title: string
          unlock_at?: string | null
          updated_at?: string
        }
        Update: {
          campaign_id?: string
          created_at?: string
          created_by?: string | null
          day_number?: number
          id?: string
          status?: string
          theme?: string | null
          title?: string
          unlock_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_days_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      media_assets: {
        Row: {
          asset_type: string
          caption: string | null
          created_at: string
          id: string
          is_featured: boolean
          storage_path: string
          tags: string[]
          uploaded_by: string | null
        }
        Insert: {
          asset_type: string
          caption?: string | null
          created_at?: string
          id?: string
          is_featured?: boolean
          storage_path: string
          tags?: string[]
          uploaded_by?: string | null
        }
        Update: {
          asset_type?: string
          caption?: string | null
          created_at?: string
          id?: string
          is_featured?: boolean
          storage_path?: string
          tags?: string[]
          uploaded_by?: string | null
        }
        Relationships: []
      }
      missions: {
        Row: {
          audience_id: string | null
          audience_type: string
          base_points: number
          created_at: string
          created_by: string | null
          description: string | null
          ends_at: string | null
          game_day_id: string
          id: string
          is_unity_challenge: boolean
          max_attempts: number | null
          moderator_approval_required: boolean
          slug: string
          starts_at: string | null
          status: string
          title: string
          unity_points: number
          updated_at: string
          wally_completion_dialogue: string | null
          wally_intro_dialogue: string | null
        }
        Insert: {
          audience_id?: string | null
          audience_type?: string
          base_points?: number
          created_at?: string
          created_by?: string | null
          description?: string | null
          ends_at?: string | null
          game_day_id: string
          id?: string
          is_unity_challenge?: boolean
          max_attempts?: number | null
          moderator_approval_required?: boolean
          slug: string
          starts_at?: string | null
          status?: string
          title: string
          unity_points?: number
          updated_at?: string
          wally_completion_dialogue?: string | null
          wally_intro_dialogue?: string | null
        }
        Update: {
          audience_id?: string | null
          audience_type?: string
          base_points?: number
          created_at?: string
          created_by?: string | null
          description?: string | null
          ends_at?: string | null
          game_day_id?: string
          id?: string
          is_unity_challenge?: boolean
          max_attempts?: number | null
          moderator_approval_required?: boolean
          slug?: string
          starts_at?: string | null
          status?: string
          title?: string
          unity_points?: number
          updated_at?: string
          wally_completion_dialogue?: string | null
          wally_intro_dialogue?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "missions_game_day_id_fkey"
            columns: ["game_day_id"]
            isOneToOne: false
            referencedRelation: "game_days"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          cta_href: string | null
          cta_label: string | null
          id: string
          message: string
          player_id: string
          read_at: string | null
          severity: string
          source_id: string | null
          source_type: string
          title: string
        }
        Insert: {
          created_at?: string
          cta_href?: string | null
          cta_label?: string | null
          id?: string
          message: string
          player_id: string
          read_at?: string | null
          severity?: string
          source_id?: string | null
          source_type: string
          title: string
        }
        Update: {
          created_at?: string
          cta_href?: string | null
          cta_label?: string | null
          id?: string
          message?: string
          player_id?: string
          read_at?: string | null
          severity?: string
          source_id?: string | null
          source_type?: string
          title?: string
        }
        Relationships: []
      }
      passport_cards: {
        Row: {
          avatar_path: string | null
          company_text: string | null
          country_flag_emoji: string | null
          country_name: string | null
          first_name: string | null
          full_name: string | null
          location_text: string | null
          passport_slug: string
          phone: string | null
          player_id: string
          updated_at: string
        }
        Insert: {
          avatar_path?: string | null
          company_text?: string | null
          country_flag_emoji?: string | null
          country_name?: string | null
          first_name?: string | null
          full_name?: string | null
          location_text?: string | null
          passport_slug?: string
          phone?: string | null
          player_id: string
          updated_at?: string
        }
        Update: {
          avatar_path?: string | null
          company_text?: string | null
          country_flag_emoji?: string | null
          country_name?: string | null
          first_name?: string | null
          full_name?: string | null
          location_text?: string | null
          passport_slug?: string
          phone?: string | null
          player_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      player_achievements: {
        Row: {
          achievement_id: string
          awarded_at: string
          id: string
          player_id: string
          source_id: string | null
          source_type: string | null
        }
        Insert: {
          achievement_id: string
          awarded_at?: string
          id?: string
          player_id: string
          source_id?: string | null
          source_type?: string | null
        }
        Update: {
          achievement_id?: string
          awarded_at?: string
          id?: string
          player_id?: string
          source_id?: string | null
          source_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "player_achievements_achievement_id_fkey"
            columns: ["achievement_id"]
            isOneToOne: false
            referencedRelation: "achievements"
            referencedColumns: ["id"]
          },
        ]
      }
      poll_options: {
        Row: {
          candidate_player_id: string | null
          id: string
          label: string
          order_index: number
          poll_id: string
        }
        Insert: {
          candidate_player_id?: string | null
          id?: string
          label: string
          order_index?: number
          poll_id: string
        }
        Update: {
          candidate_player_id?: string | null
          id?: string
          label?: string
          order_index?: number
          poll_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "poll_options_poll_id_fkey"
            columns: ["poll_id"]
            isOneToOne: false
            referencedRelation: "polls"
            referencedColumns: ["id"]
          },
        ]
      }
      polls: {
        Row: {
          campaign_id: string
          created_at: string
          created_by: string | null
          description: string | null
          ends_at: string | null
          id: string
          reason_required: boolean
          results_visibility: string
          self_vote_allowed: boolean
          starts_at: string | null
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          campaign_id: string
          created_at?: string
          created_by?: string | null
          description?: string | null
          ends_at?: string | null
          id?: string
          reason_required?: boolean
          results_visibility?: string
          self_vote_allowed?: boolean
          starts_at?: string | null
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          campaign_id?: string
          created_at?: string
          created_by?: string | null
          description?: string | null
          ends_at?: string | null
          id?: string
          reason_required?: boolean
          results_visibility?: string
          self_vote_allowed?: boolean
          starts_at?: string | null
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "polls_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_path: string | null
          country_id: string | null
          created_at: string
          email: string
          entity_id: string | null
          first_name: string | null
          full_name: string | null
          id: string
          must_change_password: boolean
          onboarding_completed: boolean
          status: string
          updated_at: string
        }
        Insert: {
          avatar_path?: string | null
          country_id?: string | null
          created_at?: string
          email: string
          entity_id?: string | null
          first_name?: string | null
          full_name?: string | null
          id: string
          must_change_password?: boolean
          onboarding_completed?: boolean
          status?: string
          updated_at?: string
        }
        Update: {
          avatar_path?: string | null
          country_id?: string | null
          created_at?: string
          email?: string
          entity_id?: string | null
          first_name?: string | null
          full_name?: string | null
          id?: string
          must_change_password?: boolean
          onboarding_completed?: boolean
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
        ]
      }
      score_events: {
        Row: {
          country_id: string | null
          created_at: string
          created_by: string | null
          id: string
          player_id: string | null
          point_type: string
          points: number
          reason: string
          reversal_of: string | null
          reversible: boolean
          source_id: string | null
          source_type: string
          squad_id: string | null
        }
        Insert: {
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          player_id?: string | null
          point_type: string
          points: number
          reason: string
          reversal_of?: string | null
          reversible?: boolean
          source_id?: string | null
          source_type: string
          squad_id?: string | null
        }
        Update: {
          country_id?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          player_id?: string | null
          point_type?: string
          points?: number
          reason?: string
          reversal_of?: string | null
          reversible?: boolean
          source_id?: string | null
          source_type?: string
          squad_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "score_events_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "score_events_reversal_of_fkey"
            columns: ["reversal_of"]
            isOneToOne: false
            referencedRelation: "score_events"
            referencedColumns: ["id"]
          },
        ]
      }
      submissions: {
        Row: {
          answer_text: string | null
          attempt_number: number
          challenge_id: string
          id: string
          moderated_at: string | null
          moderated_by: string | null
          moderation_note: string | null
          player_id: string
          selected_option_ids: string[] | null
          server_received_at: string
          status: string
          storage_path: string | null
          submitted_at: string
        }
        Insert: {
          answer_text?: string | null
          attempt_number?: number
          challenge_id: string
          id?: string
          moderated_at?: string | null
          moderated_by?: string | null
          moderation_note?: string | null
          player_id: string
          selected_option_ids?: string[] | null
          server_received_at?: string
          status?: string
          storage_path?: string | null
          submitted_at?: string
        }
        Update: {
          answer_text?: string | null
          attempt_number?: number
          challenge_id?: string
          id?: string
          moderated_at?: string | null
          moderated_by?: string | null
          moderation_note?: string | null
          player_id?: string
          selected_option_ids?: string[] | null
          server_received_at?: string
          status?: string
          storage_path?: string | null
          submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "submissions_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "challenges"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          country_id: string | null
          created_at: string
          id: string
          role: string
          user_id: string
        }
        Insert: {
          country_id?: string | null
          created_at?: string
          id?: string
          role: string
          user_id: string
        }
        Update: {
          country_id?: string | null
          created_at?: string
          id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      votes: {
        Row: {
          created_at: string
          id: string
          option_id: string
          poll_id: string
          reason: string | null
          voter_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          option_id: string
          poll_id: string
          reason?: string | null
          voter_id: string
        }
        Update: {
          created_at?: string
          id?: string
          option_id?: string
          poll_id?: string
          reason?: string | null
          voter_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "votes_option_id_fkey"
            columns: ["option_id"]
            isOneToOne: false
            referencedRelation: "poll_options"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "votes_poll_id_fkey"
            columns: ["poll_id"]
            isOneToOne: false
            referencedRelation: "polls"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_assets: {
        Row: {
          asset_type: string
          created_at: string
          id: string
          is_active: boolean
          key: string
          locale: string | null
          metadata: Json
          quality_tier: string | null
          skin_key: string | null
          storage_path: string
          updated_at: string
        }
        Insert: {
          asset_type: string
          created_at?: string
          id?: string
          is_active?: boolean
          key: string
          locale?: string | null
          metadata?: Json
          quality_tier?: string | null
          skin_key?: string | null
          storage_path: string
          updated_at?: string
        }
        Update: {
          asset_type?: string
          created_at?: string
          id?: string
          is_active?: boolean
          key?: string
          locale?: string | null
          metadata?: Json
          quality_tier?: string | null
          skin_key?: string | null
          storage_path?: string
          updated_at?: string
        }
        Relationships: []
      }
      wally_dialogues: {
        Row: {
          campaign_id: string | null
          created_at: string
          created_by: string | null
          event_type: string
          id: string
          is_active: boolean
          key: string
          locale: string
          text: string
          updated_at: string
          valid_from: string | null
          valid_until: string | null
          variant: string | null
          weight: number
        }
        Insert: {
          campaign_id?: string | null
          created_at?: string
          created_by?: string | null
          event_type: string
          id?: string
          is_active?: boolean
          key: string
          locale?: string
          text: string
          updated_at?: string
          valid_from?: string | null
          valid_until?: string | null
          variant?: string | null
          weight?: number
        }
        Update: {
          campaign_id?: string | null
          created_at?: string
          created_by?: string | null
          event_type?: string
          id?: string
          is_active?: boolean
          key?: string
          locale?: string
          text?: string
          updated_at?: string
          valid_from?: string | null
          valid_until?: string | null
          variant?: string | null
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "wally_dialogues_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_event_receipts: {
        Row: {
          acknowledged_at: string | null
          created_at: string
          cta_clicked_at: string | null
          delivered_at: string | null
          dismissed_at: string | null
          id: string
          player_id: string
          rendered_at: string | null
          wally_event_id: string
        }
        Insert: {
          acknowledged_at?: string | null
          created_at?: string
          cta_clicked_at?: string | null
          delivered_at?: string | null
          dismissed_at?: string | null
          id?: string
          player_id: string
          rendered_at?: string | null
          wally_event_id: string
        }
        Update: {
          acknowledged_at?: string | null
          created_at?: string
          cta_clicked_at?: string | null
          delivered_at?: string | null
          dismissed_at?: string | null
          id?: string
          player_id?: string
          rendered_at?: string | null
          wally_event_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wally_event_receipts_wally_event_id_fkey"
            columns: ["wally_event_id"]
            isOneToOne: false
            referencedRelation: "wally_events"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_events: {
        Row: {
          animation_key: string
          audience_id: string | null
          audience_type: string
          campaign_id: string
          cancelled_at: string | null
          created_at: string
          created_by: string | null
          cta: Json | null
          dedupe_key: string | null
          dialogue_key: string | null
          dialogue_override: string | null
          duration_ms: number | null
          effect_key: string | null
          entry_path: string | null
          event_type: string
          expires_at: string | null
          id: string
          interruptible: boolean
          position_key: string | null
          priority: string
          published_at: string | null
          requires_acknowledgement: boolean
          sound_key: string | null
          starts_at: string | null
          status: string
          variables: Json
        }
        Insert: {
          animation_key: string
          audience_id?: string | null
          audience_type: string
          campaign_id: string
          cancelled_at?: string | null
          created_at?: string
          created_by?: string | null
          cta?: Json | null
          dedupe_key?: string | null
          dialogue_key?: string | null
          dialogue_override?: string | null
          duration_ms?: number | null
          effect_key?: string | null
          entry_path?: string | null
          event_type: string
          expires_at?: string | null
          id?: string
          interruptible?: boolean
          position_key?: string | null
          priority: string
          published_at?: string | null
          requires_acknowledgement?: boolean
          sound_key?: string | null
          starts_at?: string | null
          status?: string
          variables?: Json
        }
        Update: {
          animation_key?: string
          audience_id?: string | null
          audience_type?: string
          campaign_id?: string
          cancelled_at?: string | null
          created_at?: string
          created_by?: string | null
          cta?: Json | null
          dedupe_key?: string | null
          dialogue_key?: string | null
          dialogue_override?: string | null
          duration_ms?: number | null
          effect_key?: string | null
          entry_path?: string | null
          event_type?: string
          expires_at?: string | null
          id?: string
          interruptible?: boolean
          position_key?: string | null
          priority?: string
          published_at?: string | null
          requires_acknowledgement?: boolean
          sound_key?: string | null
          starts_at?: string | null
          status?: string
          variables?: Json
        }
        Relationships: [
          {
            foreignKeyName: "wally_events_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_skins: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          key: string
          model_asset_id: string | null
          name: string
          theme_token_overrides: Json
          thumbnail_asset_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          key: string
          model_asset_id?: string | null
          name: string
          theme_token_overrides?: Json
          thumbnail_asset_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          key?: string
          model_asset_id?: string | null
          name?: string
          theme_token_overrides?: Json
          thumbnail_asset_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "wally_skins_model_asset_id_fkey"
            columns: ["model_asset_id"]
            isOneToOne: false
            referencedRelation: "wally_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wally_skins_thumbnail_asset_id_fkey"
            columns: ["thumbnail_asset_id"]
            isOneToOne: false
            referencedRelation: "wally_assets"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never
