// Generated by `mcp__supabase__generate_typescript_types` against the live
// ysjjgzakswaohmnaowmv project after applying:
//   - supabase/migrations/20260912230000_init_foundation.sql
//   - supabase/migrations/20260913000000_wally_w0_tables.sql
//
// Do not hand-edit. Regenerate after every migration
// (`mcp__supabase__generate_typescript_types`, or `supabase gen types
// typescript` once the CLI can reach this project) and commit the diff in
// the same commit as the migration that caused it.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          metadata: Json
          target_id: string | null
          target_type: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type?: string | null
        }
        Relationships: []
      }
      campaigns: {
        Row: {
          created_at: string
          ends_at: string | null
          id: string
          name: string
          slug: string
          starts_at: string | null
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          ends_at?: string | null
          id?: string
          name: string
          slug: string
          starts_at?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          ends_at?: string | null
          id?: string
          name?: string
          slug?: string
          starts_at?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      countries: {
        Row: {
          created_at: string
          flag_emoji: string | null
          id: string
          iso_code: string
          name: string
        }
        Insert: {
          created_at?: string
          flag_emoji?: string | null
          id?: string
          iso_code: string
          name: string
        }
        Update: {
          created_at?: string
          flag_emoji?: string | null
          id?: string
          iso_code?: string
          name?: string
        }
        Relationships: []
      }
      entities: {
        Row: {
          country_id: string
          created_at: string
          id: string
          name: string
        }
        Insert: {
          country_id: string
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          country_id?: string
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "entities_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_path: string | null
          country_id: string | null
          created_at: string
          email: string
          entity_id: string | null
          first_name: string | null
          full_name: string | null
          id: string
          must_change_password: boolean
          onboarding_completed: boolean
          status: string
          updated_at: string
        }
        Insert: {
          avatar_path?: string | null
          country_id?: string | null
          created_at?: string
          email: string
          entity_id?: string | null
          first_name?: string | null
          full_name?: string | null
          id: string
          must_change_password?: boolean
          onboarding_completed?: boolean
          status?: string
          updated_at?: string
        }
        Update: {
          avatar_path?: string | null
          country_id?: string | null
          created_at?: string
          email?: string
          entity_id?: string | null
          first_name?: string | null
          full_name?: string | null
          id?: string
          must_change_password?: boolean
          onboarding_completed?: boolean
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_entity_id_fkey"
            columns: ["entity_id"]
            isOneToOne: false
            referencedRelation: "entities"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          country_id: string | null
          created_at: string
          id: string
          role: string
          user_id: string
        }
        Insert: {
          country_id?: string | null
          created_at?: string
          id?: string
          role: string
          user_id: string
        }
        Update: {
          country_id?: string | null
          created_at?: string
          id?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_assets: {
        Row: {
          asset_type: string
          created_at: string
          id: string
          is_active: boolean
          key: string
          locale: string | null
          metadata: Json
          quality_tier: string | null
          skin_key: string | null
          storage_path: string
          updated_at: string
        }
        Insert: {
          asset_type: string
          created_at?: string
          id?: string
          is_active?: boolean
          key: string
          locale?: string | null
          metadata?: Json
          quality_tier?: string | null
          skin_key?: string | null
          storage_path: string
          updated_at?: string
        }
        Update: {
          asset_type?: string
          created_at?: string
          id?: string
          is_active?: boolean
          key?: string
          locale?: string | null
          metadata?: Json
          quality_tier?: string | null
          skin_key?: string | null
          storage_path?: string
          updated_at?: string
        }
        Relationships: []
      }
      wally_dialogues: {
        Row: {
          campaign_id: string | null
          created_at: string
          created_by: string | null
          event_type: string
          id: string
          is_active: boolean
          key: string
          locale: string
          text: string
          updated_at: string
          valid_from: string | null
          valid_until: string | null
          variant: string | null
          weight: number
        }
        Insert: {
          campaign_id?: string | null
          created_at?: string
          created_by?: string | null
          event_type: string
          id?: string
          is_active?: boolean
          key: string
          locale?: string
          text: string
          updated_at?: string
          valid_from?: string | null
          valid_until?: string | null
          variant?: string | null
          weight?: number
        }
        Update: {
          campaign_id?: string | null
          created_at?: string
          created_by?: string | null
          event_type?: string
          id?: string
          is_active?: boolean
          key?: string
          locale?: string
          text?: string
          updated_at?: string
          valid_from?: string | null
          valid_until?: string | null
          variant?: string | null
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "wally_dialogues_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_event_receipts: {
        Row: {
          acknowledged_at: string | null
          created_at: string
          cta_clicked_at: string | null
          delivered_at: string | null
          dismissed_at: string | null
          id: string
          player_id: string
          rendered_at: string | null
          wally_event_id: string
        }
        Insert: {
          acknowledged_at?: string | null
          created_at?: string
          cta_clicked_at?: string | null
          delivered_at?: string | null
          dismissed_at?: string | null
          id?: string
          player_id: string
          rendered_at?: string | null
          wally_event_id: string
        }
        Update: {
          acknowledged_at?: string | null
          created_at?: string
          cta_clicked_at?: string | null
          delivered_at?: string | null
          dismissed_at?: string | null
          id?: string
          player_id?: string
          rendered_at?: string | null
          wally_event_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "wally_event_receipts_wally_event_id_fkey"
            columns: ["wally_event_id"]
            isOneToOne: false
            referencedRelation: "wally_events"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_events: {
        Row: {
          animation_key: string
          audience_id: string | null
          audience_type: string
          campaign_id: string
          cancelled_at: string | null
          created_at: string
          created_by: string | null
          cta: Json | null
          dedupe_key: string | null
          dialogue_key: string | null
          dialogue_override: string | null
          duration_ms: number | null
          effect_key: string | null
          entry_path: string | null
          event_type: string
          expires_at: string | null
          id: string
          interruptible: boolean
          position_key: string | null
          priority: string
          published_at: string | null
          requires_acknowledgement: boolean
          sound_key: string | null
          starts_at: string | null
          status: string
          variables: Json
        }
        Insert: {
          animation_key: string
          audience_id?: string | null
          audience_type: string
          campaign_id: string
          cancelled_at?: string | null
          created_at?: string
          created_by?: string | null
          cta?: Json | null
          dedupe_key?: string | null
          dialogue_key?: string | null
          dialogue_override?: string | null
          duration_ms?: number | null
          effect_key?: string | null
          entry_path?: string | null
          event_type: string
          expires_at?: string | null
          id?: string
          interruptible?: boolean
          position_key?: string | null
          priority: string
          published_at?: string | null
          requires_acknowledgement?: boolean
          sound_key?: string | null
          starts_at?: string | null
          status?: string
          variables?: Json
        }
        Update: {
          animation_key?: string
          audience_id?: string | null
          audience_type?: string
          campaign_id?: string
          cancelled_at?: string | null
          created_at?: string
          created_by?: string | null
          cta?: Json | null
          dedupe_key?: string | null
          dialogue_key?: string | null
          dialogue_override?: string | null
          duration_ms?: number | null
          effect_key?: string | null
          entry_path?: string | null
          event_type?: string
          expires_at?: string | null
          id?: string
          interruptible?: boolean
          position_key?: string | null
          priority?: string
          published_at?: string | null
          requires_acknowledgement?: boolean
          sound_key?: string | null
          starts_at?: string | null
          status?: string
          variables?: Json
        }
        Relationships: [
          {
            foreignKeyName: "wally_events_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      wally_skins: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_active: boolean
          key: string
          model_asset_id: string | null
          name: string
          theme_token_overrides: Json
          thumbnail_asset_id: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          key: string
          model_asset_id?: string | null
          name: string
          theme_token_overrides?: Json
          thumbnail_asset_id?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_active?: boolean
          key?: string
          model_asset_id?: string | null
          name?: string
          theme_token_overrides?: Json
          thumbnail_asset_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "wally_skins_model_asset_id_fkey"
            columns: ["model_asset_id"]
            isOneToOne: false
            referencedRelation: "wally_assets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wally_skins_thumbnail_asset_id_fkey"
            columns: ["thumbnail_asset_id"]
            isOneToOne: false
            referencedRelation: "wally_assets"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
