/**
 * A fixed, canonical reference list (ISO 3166-1 alpha-2), used so
 * onboarding (`src/app/onboarding/`) can offer every country up front
 * rather than only whatever a previous admin happened to pre-seed into
 * `public.countries`. Picking a country not yet in that table causes the
 * onboarding server action to insert it there (get-or-create by ISO
 * code) — see `src/app/onboarding/actions.ts`. Sourced from a fixed
 * external standard specifically so the data is always correct and
 * collision-free (no risk of "Kenya" vs "kenya " duplicate rows the way
 * free-text entry would allow), unlike `entities` below it in the DB
 * model, which are genuinely free-text (ITM-specific, no external
 * standard exists for them).
 */
export type WorldCountry = { name: string; isoCode: string };

export const WORLD_COUNTRIES: WorldCountry[] = [
  { name: "Afghanistan", isoCode: "AF" },
  { name: "Albania", isoCode: "AL" },
  { name: "Algeria", isoCode: "DZ" },
  { name: "Andorra", isoCode: "AD" },
  { name: "Angola", isoCode: "AO" },
  { name: "Argentina", isoCode: "AR" },
  { name: "Armenia", isoCode: "AM" },
  { name: "Australia", isoCode: "AU" },
  { name: "Austria", isoCode: "AT" },
  { name: "Azerbaijan", isoCode: "AZ" },
  { name: "Bahamas", isoCode: "BS" },
  { name: "Bahrain", isoCode: "BH" },
  { name: "Bangladesh", isoCode: "BD" },
  { name: "Barbados", isoCode: "BB" },
  { name: "Belarus", isoCode: "BY" },
  { name: "Belgium", isoCode: "BE" },
  { name: "Belize", isoCode: "BZ" },
  { name: "Benin", isoCode: "BJ" },
  { name: "Bhutan", isoCode: "BT" },
  { name: "Bolivia", isoCode: "BO" },
  { name: "Bosnia and Herzegovina", isoCode: "BA" },
  { name: "Botswana", isoCode: "BW" },
  { name: "Brazil", isoCode: "BR" },
  { name: "Brunei", isoCode: "BN" },
  { name: "Bulgaria", isoCode: "BG" },
  { name: "Burkina Faso", isoCode: "BF" },
  { name: "Burundi", isoCode: "BI" },
  { name: "Cabo Verde", isoCode: "CV" },
  { name: "Cambodia", isoCode: "KH" },
  { name: "Cameroon", isoCode: "CM" },
  { name: "Canada", isoCode: "CA" },
  { name: "Central African Republic", isoCode: "CF" },
  { name: "Chad", isoCode: "TD" },
  { name: "Chile", isoCode: "CL" },
  { name: "China", isoCode: "CN" },
  { name: "Colombia", isoCode: "CO" },
  { name: "Comoros", isoCode: "KM" },
  { name: "Congo (Brazzaville)", isoCode: "CG" },
  { name: "Costa Rica", isoCode: "CR" },
  { name: "Croatia", isoCode: "HR" },
  { name: "Cuba", isoCode: "CU" },
  { name: "Cyprus", isoCode: "CY" },
  { name: "Czechia", isoCode: "CZ" },
  { name: "DR Congo", isoCode: "CD" },
  { name: "Denmark", isoCode: "DK" },
  { name: "Djibouti", isoCode: "DJ" },
  { name: "Dominica", isoCode: "DM" },
  { name: "Dominican Republic", isoCode: "DO" },
  { name: "Ecuador", isoCode: "EC" },
  { name: "Egypt", isoCode: "EG" },
  { name: "El Salvador", isoCode: "SV" },
  { name: "Equatorial Guinea", isoCode: "GQ" },
  { name: "Eritrea", isoCode: "ER" },
  { name: "Estonia", isoCode: "EE" },
  { name: "Eswatini", isoCode: "SZ" },
  { name: "Ethiopia", isoCode: "ET" },
  { name: "Fiji", isoCode: "FJ" },
  { name: "Finland", isoCode: "FI" },
  { name: "France", isoCode: "FR" },
  { name: "Gabon", isoCode: "GA" },
  { name: "Gambia", isoCode: "GM" },
  { name: "Georgia", isoCode: "GE" },
  { name: "Germany", isoCode: "DE" },
  { name: "Ghana", isoCode: "GH" },
  { name: "Greece", isoCode: "GR" },
  { name: "Grenada", isoCode: "GD" },
  { name: "Guatemala", isoCode: "GT" },
  { name: "Guinea", isoCode: "GN" },
  { name: "Guinea-Bissau", isoCode: "GW" },
  { name: "Guyana", isoCode: "GY" },
  { name: "Haiti", isoCode: "HT" },
  { name: "Honduras", isoCode: "HN" },
  { name: "Hungary", isoCode: "HU" },
  { name: "Iceland", isoCode: "IS" },
  { name: "India", isoCode: "IN" },
  { name: "Indonesia", isoCode: "ID" },
  { name: "Iran", isoCode: "IR" },
  { name: "Iraq", isoCode: "IQ" },
  { name: "Ireland", isoCode: "IE" },
  { name: "Israel", isoCode: "IL" },
  { name: "Italy", isoCode: "IT" },
  { name: "Ivory Coast", isoCode: "CI" },
  { name: "Jamaica", isoCode: "JM" },
  { name: "Japan", isoCode: "JP" },
  { name: "Jordan", isoCode: "JO" },
  { name: "Kazakhstan", isoCode: "KZ" },
  { name: "Kenya", isoCode: "KE" },
  { name: "Kiribati", isoCode: "KI" },
  { name: "Kuwait", isoCode: "KW" },
  { name: "Kyrgyzstan", isoCode: "KG" },
  { name: "Laos", isoCode: "LA" },
  { name: "Latvia", isoCode: "LV" },
  { name: "Lebanon", isoCode: "LB" },
  { name: "Lesotho", isoCode: "LS" },
  { name: "Liberia", isoCode: "LR" },
  { name: "Libya", isoCode: "LY" },
  { name: "Liechtenstein", isoCode: "LI" },
  { name: "Lithuania", isoCode: "LT" },
  { name: "Luxembourg", isoCode: "LU" },
  { name: "Madagascar", isoCode: "MG" },
  { name: "Malawi", isoCode: "MW" },
  { name: "Malaysia", isoCode: "MY" },
  { name: "Maldives", isoCode: "MV" },
  { name: "Mali", isoCode: "ML" },
  { name: "Malta", isoCode: "MT" },
  { name: "Mauritania", isoCode: "MR" },
  { name: "Mauritius", isoCode: "MU" },
  { name: "Mexico", isoCode: "MX" },
  { name: "Moldova", isoCode: "MD" },
  { name: "Monaco", isoCode: "MC" },
  { name: "Mongolia", isoCode: "MN" },
  { name: "Montenegro", isoCode: "ME" },
  { name: "Morocco", isoCode: "MA" },
  { name: "Mozambique", isoCode: "MZ" },
  { name: "Myanmar", isoCode: "MM" },
  { name: "Namibia", isoCode: "NA" },
  { name: "Nepal", isoCode: "NP" },
  { name: "Netherlands", isoCode: "NL" },
  { name: "New Zealand", isoCode: "NZ" },
  { name: "Nicaragua", isoCode: "NI" },
  { name: "Niger", isoCode: "NE" },
  { name: "Nigeria", isoCode: "NG" },
  { name: "North Macedonia", isoCode: "MK" },
  { name: "Norway", isoCode: "NO" },
  { name: "Oman", isoCode: "OM" },
  { name: "Pakistan", isoCode: "PK" },
  { name: "Panama", isoCode: "PA" },
  { name: "Papua New Guinea", isoCode: "PG" },
  { name: "Paraguay", isoCode: "PY" },
  { name: "Peru", isoCode: "PE" },
  { name: "Philippines", isoCode: "PH" },
  { name: "Poland", isoCode: "PL" },
  { name: "Portugal", isoCode: "PT" },
  { name: "Qatar", isoCode: "QA" },
  { name: "Romania", isoCode: "RO" },
  { name: "Rwanda", isoCode: "RW" },
  { name: "Saudi Arabia", isoCode: "SA" },
  { name: "Senegal", isoCode: "SN" },
  { name: "Serbia", isoCode: "RS" },
  { name: "Seychelles", isoCode: "SC" },
  { name: "Sierra Leone", isoCode: "SL" },
  { name: "Singapore", isoCode: "SG" },
  { name: "Slovakia", isoCode: "SK" },
  { name: "Slovenia", isoCode: "SI" },
  { name: "Somalia", isoCode: "SO" },
  { name: "South Africa", isoCode: "ZA" },
  { name: "South Korea", isoCode: "KR" },
  { name: "South Sudan", isoCode: "SS" },
  { name: "Spain", isoCode: "ES" },
  { name: "Sri Lanka", isoCode: "LK" },
  { name: "Sudan", isoCode: "SD" },
  { name: "Suriname", isoCode: "SR" },
  { name: "Sweden", isoCode: "SE" },
  { name: "Switzerland", isoCode: "CH" },
  { name: "Syria", isoCode: "SY" },
  { name: "Taiwan", isoCode: "TW" },
  { name: "Tajikistan", isoCode: "TJ" },
  { name: "Tanzania", isoCode: "TZ" },
  { name: "Thailand", isoCode: "TH" },
  { name: "Togo", isoCode: "TG" },
  { name: "Trinidad and Tobago", isoCode: "TT" },
  { name: "Tunisia", isoCode: "TN" },
  { name: "Turkey", isoCode: "TR" },
  { name: "Turkmenistan", isoCode: "TM" },
  { name: "Uganda", isoCode: "UG" },
  { name: "Ukraine", isoCode: "UA" },
  { name: "United Arab Emirates", isoCode: "AE" },
  { name: "United Kingdom", isoCode: "GB" },
  { name: "United States", isoCode: "US" },
  { name: "Uruguay", isoCode: "UY" },
  { name: "Uzbekistan", isoCode: "UZ" },
  { name: "Vanuatu", isoCode: "VU" },
  { name: "Venezuela", isoCode: "VE" },
  { name: "Vietnam", isoCode: "VN" },
  { name: "Yemen", isoCode: "YE" },
  { name: "Zambia", isoCode: "ZM" },
  { name: "Zimbabwe", isoCode: "ZW" },
].sort((a, b) => a.name.localeCompare(b.name));

/**
 * A flag emoji is just two "regional indicator symbol" code points, one
 * per letter of the ISO code (U+1F1E6 = 🇦 sits 0x45 above 'A' in ASCII,
 * i.e. the same offset for every letter) — computing it this way means
 * this file never needs a second, error-prone hand-maintained emoji per
 * country; it's mechanically derived from the one piece of data that
 * actually matters (the ISO code) and is correct for any two-letter code,
 * including ones added to `public.countries` after this file was written.
 */
export function isoToFlagEmoji(isoCode: string): string {
  const codePoints = [...isoCode.toUpperCase()].map((char) => 0x1f1e6 - 65 + char.charCodeAt(0));
  return String.fromCodePoint(...codePoints);
}
